# Generated by Django 4.0.4 on 2023-03-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id_prefix', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HardwareAppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardware_id_prefix', models.CharField(max_length=200)),
                ('default_processor', models.CharField(max_length=30)),
                ('default_ram', models.CharField(max_length=10)),
                ('default_storage', models.CharField(max_length=10)),
                ('screen_sizes', models.CharField(max_length=100)),
                ('rental_vendors', models.CharField(max_length=500)),
                ('organization_name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
