# Generated by Django 4.0.4 on 2023-03-06 16:00

import common.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id_prefix', models.CharField(default='MYORG', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HardwareAppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardware_id_prefix', models.CharField(default='LAP', max_length=255)),
                ('default_processor', models.CharField(blank=True, max_length=255, null=True)),
                ('default_ram', models.CharField(blank=True, max_length=255, null=True)),
                ('default_storage', models.CharField(blank=True, max_length=255, null=True)),
                ('screen_sizes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=common.models.get_default_screen_sizes, size=None)),
                ('rental_vendors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('organization_name', models.CharField(default='My Organization', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
