# Generated by Django 4.0.4 on 2023-03-06 14:41

from django.db import migrations

def create_initial_objects(apps, schema_editor):
    db_alias =schema_editor.connection.alias
    EmployeeAppSetting = apps.get_model('common', 'EmployeeAppSetting')
    EmployeeAppSetting.objects.using(db_alias).create(
        emp_id_prefix='MYORG'
    )
    HardwareAppSetting = apps.get_model('common', 'HardwareAppSetting')
    HardwareAppSetting.objects.using(db_alias).create(
        hardware_id_prefix='LAP',
        default_processor='i3 12th gen',
        default_ram='8GB',
        default_storage='512GB SSD',
        screen_sizes='14 inch, 15 inch',
        rental_vendors='Rental 1, Rental 2',
        organization_name='My Organization'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_objects)
    ]
