# Generated by Django 4.0.4 on 2022-08-14 08:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('designation_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=50)),
                ('dept_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.department')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalEmployee',
            fields=[
                ('emp_id', models.IntegerField(blank=True, db_index=True, editable=False)),
                ('lk_emp_id', models.CharField(db_index=True, max_length=15, null=True)),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_email', models.CharField(max_length=100)),
                ('emp_phone', models.CharField(blank=True, max_length=10, null=True)),
                ('emp_status', models.CharField(choices=[('Active', 'Active'), ('InActive', 'Inactive')], default='Active', max_length=10)),
                ('emp_date_joined', models.DateField(default=datetime.date.today)),
                ('emp_date_exited', models.DateField(blank=True, null=True)),
                ('emp_date_created', models.DateField(blank=True, editable=False)),
                ('is_assigned', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('dept_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employee.department')),
                ('desig_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employee.designation')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('loc_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employee.location')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical employee',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('lk_emp_id', models.CharField(max_length=15, null=True, unique=True)),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_email', models.CharField(max_length=100)),
                ('emp_phone', models.CharField(blank=True, max_length=10, null=True)),
                ('emp_status', models.CharField(choices=[('Active', 'Active'), ('InActive', 'Inactive')], default='Active', max_length=10)),
                ('emp_date_joined', models.DateField(default=datetime.date.today)),
                ('emp_date_exited', models.DateField(blank=True, null=True)),
                ('emp_date_created', models.DateField(auto_now_add=True)),
                ('is_assigned', models.BooleanField(default=False)),
                ('dept_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.department')),
                ('desig_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.designation')),
                ('loc_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.location')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
