# Generated by Django 4.0.4 on 2022-12-05 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('can_onboard_employee', 'Can process new employee onboarding'), ('can_exit_employee', 'Can process employee exit')]},
        ),
    ]
