# Generated by Django 4.0.4 on 2022-11-20 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employeeappsettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeAppSettings',
            new_name='EmployeeAppSetting',
        ),
    ]
