# Generated by Django 4.2.1 on 2023-06-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalemployee',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical employee', 'verbose_name_plural': 'historical employees'},
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
