# Generated by Django 4.0.1 on 2022-01-13 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('designation_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20, null=True, unique=True)),
                ('user_type', models.CharField(choices=[('User', 'User'), ('Staff', 'Staff')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=100, null=True)),
                ('emp_email', models.CharField(max_length=100, null=True)),
                ('emp_phone', models.IntegerField(null=True)),
                ('emp_status', models.CharField(choices=[('Active', 'Active'), ('InActive', 'Inactive')], max_length=10, null=True)),
                ('emp_date_created', models.DateField(auto_now_add=True)),
                ('dept_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.department')),
                ('desig_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.designation')),
                ('loc_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.location')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.user')),
            ],
        ),
    ]
