# Generated by Django 4.0.4 on 2022-11-27 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=50)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.location')),
            ],
        ),
        migrations.CreateModel(
            name='LaptopBrand',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Userz',
            fields=[
                ('user_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20, null=True, unique=True)),
                ('user_type', models.CharField(choices=[('User', 'User'), ('Staff', 'Staff')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LaptopModel',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(blank=True, max_length=50, null=True)),
                ('brand_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.laptopbrand')),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('hardware_id', models.CharField(blank=True, default=None, max_length=50, null=True, unique=True)),
                ('laptop_sr_no', models.CharField(max_length=100, unique=True)),
                ('processor', models.CharField(max_length=15)),
                ('ram_capacity', models.CharField(max_length=5)),
                ('storage_capacity', models.CharField(max_length=10)),
                ('screen_size', models.CharField(max_length=15)),
                ('screen_type', models.CharField(choices=[('Touch', 'Touch'), ('Non-Touch', 'Non-Touch')], default='Non-Touch', max_length=15, null=True)),
                ('laptop_owner_type', models.CharField(choices=[('CO', 'Company Owned'), ('Rental', 'Rental')], default='Rental', max_length=30, null=True)),
                ('laptop_rental_vendor', models.CharField(blank=True, max_length=50, null=True)),
                ('laptop_status', models.CharField(choices=[('Working', 'Working'), ('Repair', 'Repair'), ('Replace', 'Replace')], default='Working', max_length=20, null=True)),
                ('laptop_date_purchased', models.DateField(null=True)),
                ('laptop_date_sold', models.DateField(blank=True, null=True)),
                ('laptop_date_created', models.DateField(auto_now_add=True)),
                ('laptop_date_returned', models.DateField(blank=True, null=True)),
                ('laptop_return_remarks', models.TextField(blank=True, max_length=500, null=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.laptopbrand')),
                ('emp_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee')),
                ('laptop_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.location')),
                ('laptop_building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.building')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalLaptop',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True, editable=False)),
                ('hardware_id', models.CharField(blank=True, db_index=True, default=None, max_length=50, null=True)),
                ('laptop_sr_no', models.CharField(db_index=True, max_length=100)),
                ('processor', models.CharField(max_length=15)),
                ('ram_capacity', models.CharField(max_length=5)),
                ('storage_capacity', models.CharField(max_length=10)),
                ('screen_size', models.CharField(max_length=15)),
                ('screen_type', models.CharField(choices=[('Touch', 'Touch'), ('Non-Touch', 'Non-Touch')], default='Non-Touch', max_length=15, null=True)),
                ('laptop_owner_type', models.CharField(choices=[('CO', 'Company Owned'), ('Rental', 'Rental')], default='Rental', max_length=30, null=True)),
                ('laptop_rental_vendor', models.CharField(blank=True, max_length=50, null=True)),
                ('laptop_status', models.CharField(choices=[('Working', 'Working'), ('Repair', 'Repair'), ('Replace', 'Replace')], default='Working', max_length=20, null=True)),
                ('laptop_date_purchased', models.DateField(null=True)),
                ('laptop_date_sold', models.DateField(blank=True, null=True)),
                ('laptop_date_created', models.DateField(blank=True, editable=False)),
                ('laptop_date_returned', models.DateField(blank=True, null=True)),
                ('laptop_return_remarks', models.TextField(blank=True, max_length=500, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('brand', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hardware.laptopbrand')),
                ('emp_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employee.employee')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('laptop_branch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employee.location')),
                ('laptop_building', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hardware.building')),
            ],
            options={
                'verbose_name': 'historical laptop',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('emp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee')),
                ('hardware_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.laptop')),
            ],
        ),
    ]
