# Generated by Django 4.0.4 on 2022-09-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0002_historicallaptop_laptop_owner_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallaptop',
            name='screen_size',
            field=models.CharField(choices=[('14', '14 inch'), ('15', '15 inch')], default=15, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptop',
            name='screen_size',
            field=models.CharField(choices=[('14', '14 inch'), ('15', '15 inch')], default=15, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicallaptop',
            name='laptop_rental_vendor',
            field=models.CharField(blank=True, choices=[('NG', 'NextGen'), ('NC', 'NetCom')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='laptop_rental_vendor',
            field=models.CharField(blank=True, choices=[('NG', 'NextGen'), ('NC', 'NetCom')], max_length=50, null=True),
        ),
    ]
