# Generated by Django 4.0.4 on 2022-12-05 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0002_auto_20221127_2150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laptop',
            options={'permissions': [('can_return_laptop', 'Can process laptop return requests')]},
        ),
    ]
