# Generated by Django 4.0.4 on 2022-10-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0003_historicallaptop_screen_size_laptop_screen_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallaptop',
            name='screen_type',
            field=models.CharField(choices=[('Touch', 'Touch'), ('Non-Touch', 'Non-Touch')], default='Non-Touch', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='screen_type',
            field=models.CharField(choices=[('Touch', 'Touch'), ('Non-Touch', 'Non-Touch')], default='Non-Touch', max_length=15, null=True),
        ),
    ]
