# Generated by Django 4.2.1 on 2023-06-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0003_alter_laptop_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicallaptop',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical laptop', 'verbose_name_plural': 'historical laptops'},
        ),
        migrations.AlterField(
            model_name='historicallaptop',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
