# Generated by Django 4.0.1 on 2022-01-18 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0003_historicalemployee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('hardware_id', models.CharField(blank=True, max_length=50, null=True)),
                ('emp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.employee')),
            ],
        ),
    ]
