# Generated by Django 4.2.1 on 2023-11-25 16:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_historicalemployee_options_and_more'),
        ('hardware', '0004_alter_historicallaptop_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_id', models.CharField(blank=True, max_length=10, null=True)),
                ('assignment_date', models.DateField(default=datetime.datetime.now)),
                ('returned_date', models.DateField(null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modified_date', models.DateField(auto_now=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_hardwares', to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='HardwareCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HardwareOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HardwareType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LaptopOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LaptopScreenSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_range', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LaptopV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('laptop_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('processor', models.CharField(max_length=255)),
                ('ram_capacity', models.IntegerField(verbose_name='RAM (GB)')),
                ('storage_capacity', models.IntegerField(verbose_name='Storage (GB)')),
                ('is_touch', models.BooleanField(default=False)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modified_date', models.DateField(auto_now=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.laptopbrand')),
            ],
            options={
                'verbose_name': 'Laptop',
                'verbose_name_plural': 'Laptops',
            },
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('mobile_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('imei', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MobileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='laptopmodel',
            name='brand_id',
        ),
        migrations.DeleteModel(
            name='Userz',
        ),
        migrations.RemoveField(
            model_name='hardware',
            name='emp_id',
        ),
        migrations.AddField(
            model_name='hardware',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.building'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hardware',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.location'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='modified_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hardware',
            name='purchased_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='hardware',
            name='serial_no',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hardware',
            name='sold_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hardware',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True), # set to null for handling migration with new unique fields
        ),
        migrations.AlterField(
            model_name='hardware',
            name='hardware_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='LaptopModel',
        ),
        migrations.AddField(
            model_name='mobile',
            name='hardware_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hardware.hardware'),
        ),
        migrations.AddField(
            model_name='mobile',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.mobiletype'),
        ),
        migrations.AddField(
            model_name='laptopv2',
            name='hardware_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hardware.hardware'),
        ),
        migrations.AddField(
            model_name='laptopv2',
            name='screen_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.laptopscreensize'),
        ),
        migrations.AddField(
            model_name='hardwareassignment',
            name='hardware',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_assigned', to='hardware.hardware'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.hardwarecondition'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.hardwareowner'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.hardwaretype'),
        ),
    ]
