# Generated by Django 4.0.4 on 2022-11-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0004_historicallaptop_screen_type_laptop_screen_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareAppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laptop_hardware_id_prefix', models.CharField(max_length=10)),
                ('laptop_default_processor', models.CharField(max_length=10)),
                ('laptop_default_ram', models.CharField(max_length=10)),
                ('laptop_default_storage', models.CharField(max_length=10)),
                ('laptop_screen_sizes', models.CharField(max_length=100)),
                ('laptop_rental_vendors', models.CharField(max_length=100)),
            ],
        ),
    ]
