# Generated by Django 4.0.4 on 2022-11-21 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0005_hardwareappsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwareappsettings',
            name='laptop_default_processor',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='hardwareappsettings',
            name='laptop_hardware_id_prefix',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='historicallaptop',
            name='laptop_rental_vendor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicallaptop',
            name='processor',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='historicallaptop',
            name='ram_capacity',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='historicallaptop',
            name='screen_size',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='historicallaptop',
            name='storage_capacity',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='laptop_rental_vendor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='processor',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='ram_capacity',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='screen_size',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='storage_capacity',
            field=models.CharField(max_length=10),
        ),
    ]
