# Generated by Django 4.2.1 on 2023-11-04 18:08

# Migration to handle unique value generation as per:
# https://docs.djangoproject.com/en/4.2/howto/writing-migrations/#migrations-that-add-unique-fields.

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model("hardware", "Hardware")
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])

class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0005_hardwareassignment_hardwarecondition_hardwareowner_and_more'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop)
    ]
