# Generated by Django 4.0.1 on 2022-01-18 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0005_laptopbrand_laptopmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaptopMedia',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('media', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('laptop_sr_no', models.CharField(max_length=100, unique=True)),
                ('laptop_status', models.CharField(choices=[('Working', 'Working'), ('Repair', 'Repair'), ('Replace', 'Replace')], max_length=20, null=True)),
                ('laptop_date_purchased', models.DateField(null=True)),
                ('laptop_date_sold', models.DateField(null=True)),
                ('laptop_date_created', models.DateField(auto_now_add=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.laptopbrand')),
                ('hardware_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.hardware')),
                ('media', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.laptopmedia')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.laptopmodel')),
            ],
        ),
    ]
