# Generated by Django 4.0.1 on 2022-01-18 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0006_laptopmedia_laptop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='laptop_date_sold',
            field=models.DateField(blank=True, null=True),
        ),
    ]
