# Generated by Django 4.2.1 on 2023-11-04 18:08

# Migration to handle unique value generation as per:
# https://docs.djangoproject.com/en/4.2/howto/writing-migrations/#migrations-that-add-unique-fields.

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0006_populate_hardware_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
