# Generated by Django 4.0.4 on 2022-11-21 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0006_alter_hardwareappsettings_laptop_default_processor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwareappsettings',
            name='organization_name',
            field=models.CharField(default="Akash's Company", max_length=100),
            preserve_default=False,
        ),
    ]
