# Generated by Django 4.0.1 on 2022-01-18 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0007_alter_laptop_laptop_date_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='hardware_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.laptop'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='hardware_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
