# Generated by Django 4.0.1 on 2022-01-18 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0008_alter_hardware_hardware_id_alter_laptop_hardware_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='hardware_id',
            field=models.CharField(default=None, max_length=50, null=True, unique=True),
        ),
    ]
