# Generated by Django 4.0.1 on 2022-02-18 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0011_employee_user_historicalemployee_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='username',
        ),
        migrations.RemoveField(
            model_name='historicalemployee',
            name='username',
        ),
    ]
