# Generated by Django 4.0.1 on 2022-02-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0013_rename_user_userz_alter_employee_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='profilePic',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
