# Generated by Django 4.0.1 on 2022-02-23 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0015_historicalhardware'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='emp_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.employee'),
        ),
    ]
