# Generated by Django 4.0.1 on 2022-02-23 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0017_historicallaptop_delete_historicalhardware'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallaptop',
            name='emp_id',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='emp_id',
        ),
        migrations.AddField(
            model_name='employee',
            name='laptop_assiged',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.laptop'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='laptop_assiged',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hardware.laptop'),
        ),
    ]
