# Generated by Django 4.0.1 on 2022-02-23 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0018_remove_historicallaptop_emp_id_remove_laptop_emp_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='laptop_assiged',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.laptop'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='laptop_assiged',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hardware.laptop'),
        ),
    ]
