# Generated by Django 4.0.1 on 2022-02-23 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0019_alter_employee_laptop_assiged_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='laptop_assiged',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.laptop'),
        ),
    ]
