# Generated by Django 4.0.1 on 2022-03-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0020_alter_employee_laptop_assiged'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='lk_emp_id',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='lk_emp_id',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
