# Generated by Django 4.0.1 on 2022-03-02 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0021_employee_lk_emp_id_historicalemployee_lk_emp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='laptop_assiged',
        ),
        migrations.RemoveField(
            model_name='historicalemployee',
            name='laptop_assiged',
        ),
        migrations.AddField(
            model_name='historicallaptop',
            name='emp_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hardware.employee'),
        ),
        migrations.AddField(
            model_name='historicallaptop',
            name='laptop_date_returned',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicallaptop',
            name='laptop_return_remarks',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='emp_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.employee'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='laptop_date_returned',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='laptop_return_remarks',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
