# Generated by Django 4.0.1 on 2022-03-07 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0023_alter_employee_lk_emp_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallaptop',
            name='media',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='media',
        ),
        migrations.AddField(
            model_name='laptopmedia',
            name='laptop_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hardware.laptop'),
        ),
        migrations.AlterField(
            model_name='historicallaptop',
            name='hardware_id',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='hardware_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True),
        ),
    ]
