# Generated by Django 4.0.4 on 2022-06-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0025_laptopmedia_uploaded_at_alter_laptopmedia_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_phone',
            field=models.CharField(default='NA', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='emp_phone',
            field=models.CharField(default='na', max_length=10),
            preserve_default=False,
        ),
    ]
