# Generated by Django 4.0.4 on 2022-06-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0026_alter_employee_emp_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallaptop',
            name='laptop_sr_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='laptop_sr_no',
            field=models.CharField(max_length=100),
        ),
    ]
