# Generated by Django 4.0.4 on 2022-06-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0027_alter_historicallaptop_laptop_sr_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallaptop',
            name='laptop_sr_no',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='laptop_sr_no',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
