# Generated by Django 4.0.4 on 2022-06-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0031_remove_employee_profilepic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_date_joined',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='emp_date_joined',
            field=models.DateField(blank=True, null=True),
        ),
    ]
