# Generated by Django 4.0.4 on 2022-06-27 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0032_alter_employee_emp_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_date_joined',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='emp_date_joined',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
