# Generated by Django 4.0.4 on 2022-06-28 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0033_alter_employee_emp_date_joined_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=20)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.location')),
            ],
        ),
        migrations.RenameField(
            model_name='historicallaptop',
            old_name='laptop_location',
            new_name='laptop_branch',
        ),
        migrations.RenameField(
            model_name='laptop',
            old_name='laptop_location',
            new_name='laptop_branch',
        ),
        migrations.RemoveField(
            model_name='historicallaptop',
            name='model',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='model',
        ),
        migrations.AddField(
            model_name='historicallaptop',
            name='processor',
            field=models.CharField(default='i3 11th gen', max_length=15),
        ),
        migrations.AddField(
            model_name='historicallaptop',
            name='ram_capacity',
            field=models.CharField(default='8GB', max_length=5),
        ),
        migrations.AddField(
            model_name='historicallaptop',
            name='storage_capacity',
            field=models.CharField(default='512GB', max_length=10),
        ),
        migrations.AddField(
            model_name='laptop',
            name='processor',
            field=models.CharField(default='i3 11th gen', max_length=15),
        ),
        migrations.AddField(
            model_name='laptop',
            name='ram_capacity',
            field=models.CharField(default='8GB', max_length=5),
        ),
        migrations.AddField(
            model_name='laptop',
            name='storage_capacity',
            field=models.CharField(default='512GB', max_length=10),
        ),
        migrations.DeleteModel(
            name='LaptopMedia',
        ),
        migrations.AddField(
            model_name='historicallaptop',
            name='laptop_building',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hardware.building'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='laptop_building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.building'),
        ),
    ]
