# Generated by Django 4.0.4 on 2022-06-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0034_building_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='building',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='designation',
            name='designation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='laptopbrand',
            name='brand_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userz',
            name='user_type',
            field=models.CharField(choices=[('User', 'User'), ('Staff', 'Staff')], max_length=20, null=True),
        ),
    ]
