# Generated by Django 4.0.4 on 2022-06-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0034_rename_laptop_location_historicallaptop_laptop_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallaptop',
            name='model',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='model',
        ),
        migrations.AlterField(
            model_name='historicallaptop',
            name='processor',
            field=models.CharField(default='i3 11th gen', max_length=15),
        ),
        migrations.AlterField(
            model_name='historicallaptop',
            name='ram_capacity',
            field=models.CharField(default='8GB', max_length=5),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='processor',
            field=models.CharField(default='i3 11th gen', max_length=15),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='ram_capacity',
            field=models.CharField(default='8GB', max_length=5),
        ),
    ]
