# Generated by Django 4.0.4 on 2022-07-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0035_alter_building_building_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_status',
            field=models.CharField(choices=[('Active', 'Active'), ('InActive', 'Inactive')], default='Active', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='emp_status',
            field=models.CharField(choices=[('Active', 'Active'), ('InActive', 'Inactive')], default='Active', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicallaptop',
            name='laptop_status',
            field=models.CharField(choices=[('Working', 'Working'), ('Repair', 'Repair'), ('Replace', 'Replace')], default='Working', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='laptop_status',
            field=models.CharField(choices=[('Working', 'Working'), ('Repair', 'Repair'), ('Replace', 'Replace')], default='Working', max_length=20, null=True),
        ),
    ]
