# Generated by Django 4.0.4 on 2022-06-30 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0035_alter_building_building_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='laptop_assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='laptop_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
