# Generated by Django 4.0.4 on 2022-06-27 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0035_remove_historicallaptop_model_remove_laptop_model_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicallaptop',
            old_name='laptop_manufacture_date',
            new_name='laptop_date_purchased',
        ),
        migrations.RenameField(
            model_name='laptop',
            old_name='laptop_manufacture_date',
            new_name='laptop_date_purchased',
        ),
    ]
