# Generated by Django 4.0.4 on 2022-06-30 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0036_employee_laptop_assigned_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='laptop_assigned',
            new_name='is_assigned',
        ),
        migrations.RenameField(
            model_name='historicalemployee',
            old_name='laptop_assigned',
            new_name='is_assigned',
        ),
    ]
