name: miniERP CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      postgres_main:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Create env file
        run: |
          touch .env
          echo DEBUG=${{ secrets.DEBUG}} >> .env
          echo SECRET_KEY=${{ secrets.SECRET_KEY}} >> .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL}} >> .env
          echo EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER}} >> .env
          echo EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD}} >> .env
          echo EMAIL_RECIPIENTS=${{ secrets.EMAIL_RECIPIENTS}} >> .env
          cat .env

      - name: Run Tests
        env:
          DEBUG: "0"
          DJANGO_SECRET_KEY: CI_CD_TEST_KEY
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
          POSTGRES_PORT: 5432
        run: |
          python manage.py test