name: miniERP CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      postgres_main:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install virtualenv
          virtualenv venv
          . venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Create env file
        run: |
          touch .env
          echo DEBUG=${{ secrets.DEBUG}} >> .env
          echo SECRET_KEY=${{ secrets.SECRET_KEY}} >> .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL}} >> .env
          echo EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER}} >> .env
          echo EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD}} >> .env
          echo EMAIL_RECIPIENTS=${{ secrets.EMAIL_RECIPIENTS}} >> .env
          echo ENVIRONMENT=${{ secrets.ENVIRONMENT}} >> .env
          echo DB_ENGINE=${{ secrets.DB_ENGINE}} >> .env
          echo DB_NAME=${{ secrets.DB_NAME}} >> .env
          echo DB_USER=${{ secrets.DB_USER}} >> .env
          echo DB_USER_PASS=${{ secrets.DB_USER_PASS}} >> .env
          echo REDIS_PASS=${{ secrets.REDIS_PASS}} >> .env

          cat .env

      - name: Install locales (for int to currency conversion)
        run: |
          sudo apt-get update
          sudo apt-get -y install language-pack-en
      
      - name: Create Log File
        run: |
          sudo mkdir /var/log/django
          sudo touch /var/log/django/django.log
          sudo chown -R $USER:$USER /var/log/django/django.log

      - name: Run Tests
        env:
          DEBUG: "0"
          DJANGO_SECRET_KEY: CI_CD_TEST_KEY
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
          POSTGRES_PORT: 5432
        run: |
          . venv/bin/activate
          python manage.py migrate
          python manage.py test